# 3. Array Operation

#### 1. Arithmatic Operations on numpy Arrays
    Numpy supports element-wise arithmatic between arrays of the same shape. 

In [1]:
import numpy as np

a = np.array([4,6,8])
b = np.array([3,6,2])

#element-wise arithmatic operations
addition_1 = a + b

substraction_2 = a - b

multiplication_3 = a * b

division_4 = a / b

power_a = a ** 2

power_b = b ** 2
print("sum:", addition_1)
print("difference:", substraction_2)
print("product:", multiplication_3)
print("division:", division_4)
print("power of a:", power_a)
print("power of b:", power_b)

sum: [ 7 12 10]
difference: [1 0 6]
product: [12 36 16]
division: [1.33333333 1.         4.        ]
power of a: [16 36 64]
power of b: [ 9 36  4]


#### 2.Broadcasting in NumPy

    Broadcasting is a powerful mechanism in NumPy that allows operations between arrays of different shapes. It enables efficient computations without the need to explicitly create intermediate arrays, leading to significant performance gains.

* Key Rules of Broadcasting:

Rule 1: Shape Compatibility

Arrays must have compatible shapes for broadcasting to occur.
Two dimensions are compatible when:
* They are equal.
* One of them is 1.
  
Rule 2: Implicit Expansion

Dimensions of size 1 are stretched or "broadcast" to match the corresponding dimension of the other array.

In [2]:
import numpy as np

a = np.array([1, 2, 3])  # Shape: (3,)
b = np.array([4])       # Shape: (1,)

result = a + b  
print("Array brodcasting is:", result)

Array brodcasting is: [5 6 7]


In [3]:
a = np.array([1, 2, 3])
b = 2

result = a * b  
print("Scalar Broadcasting:", result)


Scalar Broadcasting: [2 4 6]


In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])  # B is broadcasted across rows

result = A + B
print("Array Broadcasting:\n", result)

Array Broadcasting:
 [[2 4 6]
 [5 7 9]]


#### 3.Element-wise Operations and Functions
    Element-wise operations and functions in NumPy operate on each element of an array independently. This is often more efficient than using loops in Python, especially for large arrays.

In [5]:
import numpy as np

a = np.array([1, 2, 3])

result_sqrt = np.sqrt(a)
result_sin = np.sin(a)    
result_cos = np.cos(a)
result_exp = np.exp(a)
result_log = np.exp(a)
result_abs = np.abs(a)

print("square root of a :", result_sqrt)
print("sine of a:", result_sin)
print("cosine of a:", result_cos)
print("exponential of a:", result_exp)
print("natural logarithm of a:", result_log)
print("absolute value of a:", result_abs )

square root of a : [1.         1.41421356 1.73205081]
sine of a: [0.84147098 0.90929743 0.14112001]
cosine of a: [ 0.54030231 -0.41614684 -0.9899925 ]
exponential of a: [ 2.71828183  7.3890561  20.08553692]
natural logarithm of a: [ 2.71828183  7.3890561  20.08553692]
absolute value of a: [1 2 3]


# 4. Array Shapes and Reshaping

#### 1.Checking array dimensions with .shape and .ndim.

##### .shape :
        Returns a tuple representing the dimensions of the array.

In [6]:
import numpy as np

arr = np.array([[3, 3, 5], [5, 3, 2]])
print(arr.shape)


(2, 3)


In [7]:
arr = np.array([[[3, 3, 5], [5, 3, 2], [7, 4, 2]]])
print(arr.shape)


(1, 3, 3)


#### .ndim: 
    Returns the number of dimensions (or axes) of the array.

In [8]:
arr = np.array([[3, 3, 5], [5, 3, 2]])
print(arr.ndim)

arr = np.array([[[3, 3, 5], [5, 3, 2], [7, 4, 2]]])
print(arr.ndim)


2
3


#### 2.Changing Array Shape with  .reshape(), .flatten(), .transpose().

#### .reshape()
    Reshapes the array to a new shape while keeping the same data.

In [9]:
arr = np.array([3, 2, 7, 6, 2, 4])
new_arr = arr.reshape(3,2)
print(new_arr)

[[3 2]
 [7 6]
 [2 4]]


In [10]:
arr = np.array([3, 2, 7, 6, 2, 4])
new_arr = arr.reshape(2,3)
print(new_arr)

[[3 2 7]
 [6 2 4]]


#### .flatten():
    Converts the array into a 1D array by flattening all dimensions.

In [11]:
arr = np.array([[2,4], [1,2]])
flat_arr = arr.flatten()
print(flat_arr)

[2 4 1 2]


In [12]:
arr = np.array([[[2,4], [1,2],[6,3]]])
flat_arr = arr.flatten()
print(flat_arr)

[2 4 1 2 6 3]


#### .transpose():
    Switches the axes of the array. For a 2D array, it swaps rows and columns.

In [13]:
arr = np.array([[1, 2], [3, 4]]) 
transposed_arr = arr.transpose() 
print(transposed_arr)

[[1 3]
 [2 4]]


In [14]:
arr = np.array([[[1, 2, 2], [4, 5, 1], [6,8,2]]])
transposed_arr = arr.transpose()
print(transposed_arr)

[[[1]
  [4]
  [6]]

 [[2]
  [5]
  [8]]

 [[2]
  [1]
  [2]]]


#### 3. Concatenating and splitting arrays using np.concatenate(), np.vstack(), np.hstack(), np.split().


#### np.concatenate() : 
Concatenates arrays along a specified axis.

In [15]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_arr = np.concatenate((arr1, arr2), axis=0)  # Concatenate vertically
print(concatenated_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_arr = np.concatenate((arr1, arr2), axis=1)  # Concatenate horizontally
print(concatenated_arr)

[[1 2 5 6]
 [3 4 7 8]]


#### np.vstack():
Concatenates arrays vertically (row-wise).

In [17]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
vstack_arr = np.vstack((arr1, arr2))
print(vstack_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### np.hstack(): 
Concatenates arrays horizontally (column-wise).

In [18]:
hstack_arr = np.hstack((arr1, arr2))
print(hstack_arr)

[[1 2 5 6]
 [3 4 7 8]]


#### np.split():
Splits an array into multiple sub-arrays along a specified axis

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)  # Split into 3 equal parts
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 2)  # Split into  2 equal parts
print(split_arr)

[array([1, 2, 3]), array([4, 5, 6])]
