# 5. Array Manipulation

#### 1).Indexing and Slicing:

In [20]:
import numpy as np

arr = np.array([[1, 3, 5], [4, 6 ,3]])
# Accessing Elements:
print(arr[0,2])
print(arr[1,2])

# slicing subarray:
print(arr[0:2])
print(arr[:, 1])
print(arr[1, 1:])

5
3
[[1 3 5]
 [4 6 3]]
[3 6]
[6 3]


#### 2).Masking (Logical Indexing)
Masking, also known as boolean indexing, is a powerful technique in NumPy that allows you to select elements from an array based on a boolean condition.


In [26]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr != 2
print(arr[mask])  

[1 3 4 5]


In [23]:
arr = np.array([4, 2, 7, 1, 3, 5])
mask = arr >2
print(arr[mask])

[4 7 3 5]


#### 3).Fancy Indexing
Fancy indexing allows for flexible selection of elements using arrays of indices.

In [27]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4]) 

selected_elements = data[indices] 
print(selected_elements)  

[10 30 50]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 2])
cols = np.array([1, 2])

selected_elements = arr[rows, cols] 
print(selected_elements) 

[2 9]


# 6. Mathematical Functions

### 1)Universal functions (ufuncs) like np.add(), np.subtract(), np.multiply().

. Universal Functions (ufuncs):

Concept: Ufuncs are element-wise operations that operate on NumPy arrays. They perform calculations on corresponding elements between two arrays or between an array and a scalar value.

In [40]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.add(arr1, arr2)  
print(result)

result = np.subtract(arr1, arr2)  
print(result)

result = np.multiply(arr1, arr2)  
print(result)

result = np.log(arr1)  
print(result)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.         0.69314718 1.09861229]


### 2. Statistical Functions:
np.mean(), np.median(), np.std(), np.var(), np.min(), np.max().

These functions compute various statistical measures on NumPy arrays. They are helpful for summarizing and analyzing data.

In [43]:
arr = np.array([10, 15, 20, 25, 30])

mean_value = np.mean(arr)
std_dev = np.std(arr)
median_value = np.median(arr)
var_value = np.var(arr)
min_value = np.min(arr)
max_value = np.max(arr)

print("Mean:", mean_value) 
print("Standard Deviation:", std_dev) 
print("median:", median_value )
print("variance:", var_value )
print("minimum:", min_value)
print("maximum:", max_value)

Mean: 20.0
Standard Deviation: 7.0710678118654755
median: 20.0
variance: 50.0
minimum: 10
maximum: 30


### 3.Linear algebra functions: 
np.dot(), np.matmul(), np.linalg.inv(), np.linalg.eig().

##### np.dot:
Performs the dot product of two arrays.

In [45]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot_product = np.dot(v1, v2) 
print(dot_product) 

32


#### np.matmul(): 
Computes the matrix multiplication of two arrays.

In [50]:
mat_1 = np.array([[1, 2], [3, 4]])
mat_2 = np.array([[5, 6, 1], [7, 8, 2]])

product = np.matmul(mat_1, mat_2) 
print(product) 

[[19 22  5]
 [43 50 11]]


In [47]:
mat_1 = np.array([[3, 2], [2, 4]])
mat_2 = np.array([[1, 3], [3, 2]])

mat_product = np.matmul(mat_1,mat_2)
print(mat_product)

[[ 9 13]
 [14 14]]


#### np.linalg.inv(): 
Calculates the inverse of a square matrix.

In [56]:
matrix = np.array([[1,2], [3,4]])
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


#### np.linalg.eig():
Computes the eigenvalues and eigenvectors of a square matrix.


In [60]:
import numpy as np

a = np.array([[1, 2], [3, 4]]) 
w, v = np.linalg.eig(a)

print("Eigenvalues:", w)  
print("Eigenvectors:\n", v)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [62]:
b = np.array([[43, 2], [3, 23]])
W, v = np.linalg.eig(a)
print("Eigenvalues:",W)
print("Eigenvectors:", v)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
