# 1. Introduction to Numpy

### Why is NumPy Important?

### Installation of NumPy

In [4]:
pip install numpy                   

In [2]:
import numpy as np
print(np.__version__)  # Check installed version


1.26.4


### Role of numpy in data science, machine learning, and scientific computing.


### 2. Arrays in NumPy

### Creating arrays using np.array(), np.zeros(), np.ones(), np.arange(), and np.linspace().

#### 1.  np.array()

In [15]:
import numpy as np
a = np.array([2,5,2,7])
print(a)

[2 5 2 7]


In [16]:
type(a)

numpy.ndarray

In [17]:
b = np.array([6,3,9,3])
b

array([6, 3, 9, 3])

#### 2. np.zeros()
Creates an array filled with zeros.

In [22]:
x = np.zeros([5, 7])
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
y = np.zeros([4,2])
y

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### 3.np.ones()
    numpy.ones() is a function in NumPy that creates a new array filled with ones. It allows you to specify the dimensions (shape) of the array by providing the desired shape as an argument or a tuple of dimensions .


In [32]:
arr = np.ones([4,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
arr = np.ones((3, 4))  # 3x4 array of ones
print(arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 4.np.arange()
Generates an array with a sequence of numbers, similar to Python's range(), but returns an array.


In [42]:
arr = np.arange(2, 12, 3)  
print(arr)

[ 2  5  8 11]


In [43]:
arr = np.arange(5,9,1)
arr

array([5, 6, 7, 8])

#### 5.np.linspace()

In [49]:
a = np.linspace(2,4)
a

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [54]:
a = np.linspace(23,51, retstep=True)                     # retstep : step size bet elements.
a

(array([23.        , 23.57142857, 24.14285714, 24.71428571, 25.28571429,
        25.85714286, 26.42857143, 27.        , 27.57142857, 28.14285714,
        28.71428571, 29.28571429, 29.85714286, 30.42857143, 31.        ,
        31.57142857, 32.14285714, 32.71428571, 33.28571429, 33.85714286,
        34.42857143, 35.        , 35.57142857, 36.14285714, 36.71428571,
        37.28571429, 37.85714286, 38.42857143, 39.        , 39.57142857,
        40.14285714, 40.71428571, 41.28571429, 41.85714286, 42.42857143,
        43.        , 43.57142857, 44.14285714, 44.71428571, 45.28571429,
        45.85714286, 46.42857143, 47.        , 47.57142857, 48.14285714,
        48.71428571, 49.28571429, 49.85714286, 50.42857143, 51.        ]),
 0.5714285714285714)

# Array Indexing:

In [ ]:
    - Indexing in Numpy refers to accessing and retrieving specific elements or groups of elements from an array. Numpy arrays can be multidimensional,
so indexing allows you to access elements along with different dimensions of the array.

In [56]:
arr = np.array ([ 3,6,2,7,2])
print(arr[3])

print(arr[1:5])

7
[6 2 7 2]


In [77]:
arr = np.array ([[2,4,1], [5,7,3], [6,4,2]])
print(arr[2,2])

print(arr[0,-2])

print(arr[-2,2])

print(arr[2,0])

2
4
[[2 4 1]]
3
6


# slicing 

In [78]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Output: [20, 30, 40] (from index 1 to 3)
print(arr[:3])   # Output: [10, 20, 30] (first 3 elements)

[20 30 40]
[10 20 30]


In [80]:
arr = np.array([2,6,23,14,5])
print(arr[1:3])

print(arr[-2:4])

[ 6 23]
[14]


In [87]:
arr = np.array ([[2,4,1], [5,7,3], [6,4,2]])
print(arr[1:3])

print(arr[-1:-3])               # excluding -3

[[5 7 3]
 [6 4 2]]
[]
