# 7. Random Number Generation
Random number generation is the process of creating a sequence of numbers that appear to be random.

## 1.Generating random numbers using np.random (e.g., np.random.rand(), np.random.randint()).

### np.random.rand():
It will generate random value between 0-l and reshape(x,y) to craete x*y matrix.

In [1]:
import numpy as np
import random

In [2]:
data = np.random.rand(1,20)
print(data)

[[0.41404776 0.00725292 0.54747396 0.49301392 0.01703885 0.89001816
  0.42377463 0.02128699 0.06108657 0.80788618 0.71289389 0.55532762
  0.4643384  0.80306945 0.57254508 0.98435476 0.51851251 0.1505844
  0.87356165 0.48111839]]


In [3]:
len(data)

1

In [4]:
data = np.random.rand(2,10)
print(data)
len(data)

[[0.1175199  0.39824774 0.40131781 0.47862102 0.05077477 0.6073821
  0.69266662 0.70409129 0.31362655 0.67795033]
 [0.3061125  0.24566136 0.50505438 0.49655286 0.33310614 0.41603769
  0.06240579 0.7278799  0.61583327 0.74287715]]


2

### randint():
Generates random integers from a given range

In [5]:
random_int = np.random.randint(0,11,6)
print(random_int)

[ 8 10  4  2  4  9]


In [6]:
random_int = np.random.randint(1,30,4)
print(random_int)

[26 19 20 17]


### np.random.randn():
Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

In [7]:
random_normal = np.random.randn(10)
print(random_normal)

[ 0.83534045 -0.21359044 -1.19744295  0.02111756  0.24923685 -0.25876204
 -0.78704148  2.01826588 -0.23870271  1.32258696]


In [8]:
random_normal = np.random.randn(10,2)
print(random_normal)

[[ 1.9867478  -1.00739273]
 [ 0.29612123 -0.46696779]
 [-0.43530389  0.58674808]
 [ 1.04076451  0.42261307]
 [-1.84516672  0.18088064]
 [ 1.02252262 -1.05891618]
 [ 0.459601   -0.92713067]
 [ 1.25057838  0.66029955]
 [-0.17650316 -0.79400485]
 [ 0.69212255 -1.8166661 ]]


### ranf() :
generates random floats in the half-open interval [0.0, 1.0).

In [9]:
random_f = np.random.ranf(10)
random_f

array([0.47503185, 0.17062484, 0.91773412, 0.45054321, 0.50316012,
       0.93328968, 0.59427039, 0.50742278, 0.2648453 , 0.65579269])

### random():
ranf and random are both same function in np.random()

In [10]:
random_num = np.random.random(21)
random_num

array([0.33431749, 0.48353557, 0.14829767, 0.37438252, 0.64215874,
       0.39291126, 0.75546161, 0.55821112, 0.0169313 , 0.73548216,
       0.03492883, 0.80247475, 0.97952371, 0.65558176, 0.23116829,
       0.1118404 , 0.58641975, 0.92372864, 0.29785926, 0.90653735,
       0.10250486])

## Seeding Random Number Generation:
np.random.seed(): Sets the seed for the random number generator. This ensures that the same sequence of random numbers is generated each time 
the code is run with the same seed.   

    

In [11]:
arr = np.random.seed(12)
arr1 = np.random.rand(4)
arr1

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939])

In [12]:
arr = np.random.seed(112)
arr1 = np.random.rand(6)
arr1

array([0.37505713, 0.64030462, 0.95001658, 0.0756772 , 0.77692966,
       0.83274576])

## Random Sampling, Shuffling, and Permutations

### np.random.choice(): 
Draws a given number of samples from a given array or sequence with or without replacement.

In [13]:
data = np.array([2,4,2,1,5,6])
sample = np.random.choice(data, 7, replace = True) # replace=True allows sampling with duplicates
sample

array([2, 2, 6, 5, 2, 6, 2])

In [14]:

data = np.array([1, 2, 3, 4, 5])
samples = np.random.choice(data, 5, replace=False)  # replace=False don't allows sampling with duplicates
print(samples)

[3 1 2 5 4]


### np.random.shuffle():
Shuffles the elements of an array in-place.

In [15]:
arr = np.array([1, 2, 3, 4, 5])
sample = np.random.shuffle(arr)
print(arr)

[3 1 4 2 5]


In [16]:
data = np.array([12, 23, 13, 24, 51])
sample = np.random.shuffle(data)
print(data)

[12 51 13 23 24]


### np.random.permutation():
Returns a permuted copy of an array or a sequence of integers.

In [17]:
data = np.array([1,  4, 5, 3, 8])
permutation_sample = np.random.permutation(data)
print(data)

[1 4 5 3 8]


In [18]:
data = np.array([1, 2, 3, 4, 5])
permuted_data = np.random.permutation(data)
print(permuted_data)

[4 2 1 3 5]


# 8. Broadcasting

Broadcasting is a powerful mechanism in NumPy that allows operations between arrays of different shapes, as long as certain compatibility rules are met. It avoids the need to explicitly create intermediate arrays, making your code more concise and efficient.

Rules of broadcasting (e.g., matching dimensions, aligning axes).

Arrays must have compatible shapes along each dimension.
Dimensions are compatible when they are equal or one of them is 1.

Arrays are aligned based on their trailing (rightmost) dimensions.
Dimensions of size 1 are stretched or broadcast to match the corresponding dimension of the other array.

In [19]:
arr1 = np.array([1,2,2])
arr2 = 4
print(arr1 * arr2)

[4 8 8]


In [20]:
arr = np.array([4,3,2])
arr1 = np.array([[2,1,3], [4,2,3]])
print(arr + arr1)

[[6 4 5]
 [8 5 5]]


In [21]:
arr = np.array([2])
arr1= np.random.randn(3)
print(arr - arr1)

[3.22640489 1.83271268 0.7961579 ]
